[mypy]
python_version = 3.9
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
disallow_incomplete_defs = False

# Add any modules you want to ignore
[mypy.plugins.numpy.*]
ignore_missing_imports = True

# You can add specific modules from your project
[mypy.Gaming.*]
ignore_missing_imports = False
